# Generated by Django 4.2.7 on 2023-11-23 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-applicationDate']},
        ),
        migrations.RenameField(
            model_name='job',
            old_name='gotFeedback',
            new_name='feedback',
        ),
        migrations.AddField(
            model_name='job',
            name='ordinalNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='coverLetterFile',
            field=models.FileField(blank=True, upload_to='upload'),
        ),
        migrations.AlterField(
            model_name='job',
            name='cvFile',
            field=models.FileField(upload_to='upload'),
        ),
    ]
