# Generated by Django 4.2.7 on 2023-11-23 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_options_rename_gotfeedback_job_feedback_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='ordinalNumber',
        ),
    ]
